# Generated by Django 4.1 on 2024-03-16 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("coach_appointment_system", "0003_alter_coach_appointment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coach_appointment",
            name="booking_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
