# Generated by Django 4.1 on 2024-03-15 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.CharField(max_length=9)),
            ],
            options={"verbose_name_plural": "Day", "db_table": "master_day",},
        ),
        migrations.CreateModel(
            name="Time",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.TimeField(unique=True)),
            ],
            options={"verbose_name_plural": "Time", "db_table": "master_time",},
        ),
        migrations.CreateModel(
            name="UTC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offset", models.CharField(max_length=1)),
                ("hour", models.TimeField()),
                ("zone", models.CharField(max_length=100, unique=True)),
            ],
            options={"verbose_name_plural": "UTC", "db_table": "master_utc",},
        ),
        migrations.CreateModel(
            name="Coach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "utc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="master.utc"
                    ),
                ),
            ],
            options={"verbose_name_plural": "Coach", "db_table": "master_coach",},
        ),
    ]
