# Generated by Django 4.1 on 2024-03-15 00:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utc",
            name="offset",
            field=models.CharField(
                max_length=1,
                validators=[django.core.validators.RegexValidator(regex="^[+-]$")],
            ),
        ),
    ]
